### ISSUE TITLE
"Quirky Syntax" refers to non-syntactic issues

### ISSUE THREAD

**Issue by fdr** [brandur/org#8]
```
Quirky syntax: Go is littered with quirky syntax that’s fine once you know it, but is unnecessarily opaque. Some examples:
The distinction between new, make, and initialization with composite literals.
Interfaces are always references.
Symbols that start with capital letters are exported from packages.
Channels created without a size are blocking.
select blocks with a default case become non-blocking.
You check if a key exists in a map by using a rare second return value of a normal lookup with square brackets.
Named return values.
Closing a channel causes any Goroutine that was listening on it to fall through having received a zero value of the channel’s type.
Comparing interfaces to nil is allowed by the compiler, but apparently not a good idea, and can lead to some strange bugs.
```

A good number of these could be considered semantics: they don't have much to do with odd grammatical construction. Some are both.

**Comment by brandur** [comment]
Good point! Thank-you Farina. I've re-worded this section a bit in 094fbfa. Let me know what you think.

Just out of curiosity: where did you get linked to this? I saw an uptick an interest over the last day or so, but didn't really notice it on any major aggregators.

**Comment by fdr** [comment]
Twitter. I saw it when you posted it, read it, saw it again, and re-read it
more carefully for no particular reason.

**Comment by brandur** [comment]
> Twitter. I saw it when you posted it, read it, saw it again, and re-read it more carefully for no particular reason.

Hah, cool. Well thanks for doing so!
